
    // Auto-generated by scripts/build-components-bundle.ts
    // Defines window.UBITS and attaches all components

    window.UBITS = window.UBITS || {};
    console.log('🔧 Initializing UBITS Components Bundle...');
    
            import * as Accordion from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/accordion/src/index.ts';
            window.UBITS.Accordion = Accordion;
            import '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/accordion/src/styles/accordion.css';

            import * as Alert from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/alert/src/index.ts';
            window.UBITS.Alert = Alert;
            import '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/alert/src/styles/alert-debug.css';
import '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/alert/src/styles/alert.css';

            import * as Avatar from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/avatar/src/index.ts';
            window.UBITS.Avatar = Avatar;
            import '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/avatar/src/styles/avatar.css';

            import * as Badge from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/badge/src/index.ts';
            window.UBITS.Badge = Badge;
            import '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/badge/src/styles/badge.css';

            import * as BarMetricCard from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/bar-metric-card/src/index.ts';
            window.UBITS.BarMetricCard = BarMetricCard;
            import '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/bar-metric-card/src/styles/bar-metric-card.css';

            import * as Breadcrumb from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/breadcrumb/src/index.ts';
            window.UBITS.Breadcrumb = Breadcrumb;
            import '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/breadcrumb/src/styles/breadcrumb.css';

            import * as Button from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/button/src/index.ts';
            window.UBITS.Button = Button;
            import '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/button/src/styles/button.css';

            import * as ButtonAi from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/button-ai/src/index.ts';
            window.UBITS.ButtonAi = ButtonAi;
            import '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/button-ai/src/styles/button-ai.css';

            import * as ButtonFeedback from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/button-feedback/src/index.ts';
            window.UBITS.ButtonFeedback = ButtonFeedback;
            import '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/button-feedback/src/styles/button-feedback.css';

            import * as Calendar from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/calendar/src/index.ts';
            window.UBITS.Calendar = Calendar;
            import '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/calendar/src/styles/calendar.css';

            import * as Card from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/card/src/index.ts';
            window.UBITS.Card = Card;
            import '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/card/src/styles/card.css';
import '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/card/src/styles/simple-card.css';

            import * as Carousel from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/carousel/src/index.ts';
            window.UBITS.Carousel = Carousel;
            import '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/carousel/src/styles/carousel.css';

            import * as Checkbox from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/checkbox/src/index.ts';
            window.UBITS.Checkbox = Checkbox;
            import '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/checkbox/src/styles/checkbox.css';

            import * as Chip from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/chip/src/index.ts';
            window.UBITS.Chip = Chip;
            import '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/chip/src/styles/chip.css';

            import * as CsatMetricCard from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/csat-metric-card/src/index.ts';
            window.UBITS.CsatMetricCard = CsatMetricCard;
            import '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/csat-metric-card/src/styles/csat-metric-card.css';

            import * as DataTable from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/data-table/src/index.ts';
            window.UBITS.DataTable = DataTable;
            import '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/data-table/src/styles/data-table.css';

            import * as DataView from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/data-view/src/index.ts';
            window.UBITS.DataView = DataView;
            import '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/data-view/src/styles/data-view.css';

            import * as Drawer from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/drawer/src/index.ts';
            window.UBITS.Drawer = Drawer;
            import '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/drawer/src/styles/drawer.css';

            import * as EmptyState from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/empty-state/src/index.ts';
            window.UBITS.EmptyState = EmptyState;
            import '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/empty-state/src/styles/empty-state.css';

            import * as FileUpload from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/file-upload/src/index.ts';
            window.UBITS.FileUpload = FileUpload;
            import '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/file-upload/src/styles/file-upload.css';

            import * as Gallery from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/gallery/src/index.ts';
            window.UBITS.Gallery = Gallery;
            import '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/gallery/src/styles/gallery.css';

            import * as HeaderSection from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/header-section/src/index.ts';
            window.UBITS.HeaderSection = HeaderSection;
            import '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/header-section/src/styles/header-section.css';

            import * as Input from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/input/src/index.ts';
            window.UBITS.Input = Input;
            import '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/input/src/styles/input.css';

            import * as List from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/list/src/index.ts';
            window.UBITS.List = List;
            import '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/list/src/styles/list.css';

            import * as Mask from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/mask/src/index.ts';
            window.UBITS.Mask = Mask;
            import '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/mask/src/styles/mask.css';

            import * as Menu from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/menu/src/index.ts';
            window.UBITS.Menu = Menu;
            import '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/menu/src/styles/menu.css';

            import * as MetricCard from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/metric-card/src/index.ts';
            window.UBITS.MetricCard = MetricCard;
            import '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/metric-card/src/styles/metric-card.css';

            import * as Modal from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/modal/src/index.ts';
            window.UBITS.Modal = Modal;
            import '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/modal/src/styles/modal.css';

            import * as NpsCard from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/nps-card/src/index.ts';
            window.UBITS.NpsCard = NpsCard;
            import '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/nps-card/src/styles/nps-card.css';

            import * as Pagination from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/pagination/src/index.ts';
            window.UBITS.Pagination = Pagination;
            import '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/pagination/src/styles/pagination.css';

            import * as ParticipantsMenu from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/participants-menu/src/index.ts';
            window.UBITS.ParticipantsMenu = ParticipantsMenu;
            import '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/participants-menu/src/styles/participants-menu.css';

            import * as Popover from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/popover/src/index.ts';
            window.UBITS.Popover = Popover;
            import '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/popover/src/styles/popover.css';

            import * as Progress from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/progress/src/index.ts';
            window.UBITS.Progress = Progress;
            import '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/progress/src/styles/progress.css';

            import * as ProgressGeneralCard from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/progress-general-card/src/index.ts';
            window.UBITS.ProgressGeneralCard = ProgressGeneralCard;
            import '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/progress-general-card/src/styles/progress-general-card.css';

            import * as RadioButton from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/radio-button/src/index.ts';
            window.UBITS.RadioButton = RadioButton;
            import '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/radio-button/src/styles/radio-button.css';

            import * as SaveIndicator from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/save-indicator/src/index.ts';
            window.UBITS.SaveIndicator = SaveIndicator;
            import '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/save-indicator/src/styles/save-indicator.css';

            import * as ScoreCardMetrics from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/score-card-metrics/src/index.ts';
            window.UBITS.ScoreCardMetrics = ScoreCardMetrics;
            import '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/score-card-metrics/src/styles/score-card-metrics.css';

            import * as Scroll from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/scroll/src/index.ts';
            window.UBITS.Scroll = Scroll;
            import '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/scroll/src/styles/scroll.css';

            import * as SearchButton from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/search-button/src/index.ts';
            window.UBITS.SearchButton = SearchButton;
            import '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/search-button/src/styles/search-button.css';

            import * as SegmentControl from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/segment-control/src/index.ts';
            window.UBITS.SegmentControl = SegmentControl;
            import '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/segment-control/src/styles/segment-control.css';

            import * as SelectionCard from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/selection-card/src/index.ts';
            window.UBITS.SelectionCard = SelectionCard;
            import '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/selection-card/src/styles/selection-card.css';

            import * as Sidebar from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/sidebar/src/index.ts';
            window.UBITS.Sidebar = Sidebar;
            import '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/sidebar/src/styles/sidebar.css';

            import * as Skeleton from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/skeleton/src/index.ts';
            window.UBITS.Skeleton = Skeleton;
            import '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/skeleton/src/styles/skeleton.css';

            import * as Slider from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/slider/src/index.ts';
            window.UBITS.Slider = Slider;
            import '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/slider/src/styles/slider.css';

            import * as Spinner from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/spinner/src/index.ts';
            window.UBITS.Spinner = Spinner;
            import '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/spinner/src/styles/spinner.css';

            import * as StatsCard from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/stats-card/src/index.ts';
            window.UBITS.StatsCard = StatsCard;
            import '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/stats-card/src/styles/stats-card.css';

            import * as StatusTag from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/status-tag/src/index.ts';
            window.UBITS.StatusTag = StatusTag;
            import '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/status-tag/src/styles/status-tag.css';

            import * as Stepper from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/stepper/src/index.ts';
            window.UBITS.Stepper = Stepper;
            import '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/stepper/src/styles/stepper.css';

            import * as Subnav from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/subnav/src/index.ts';
            window.UBITS.Subnav = Subnav;
            import '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/subnav/src/styles/subnav.css';

            import * as Tabbar from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/tabbar/src/index.ts';
            window.UBITS.Tabbar = Tabbar;
            import '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/tabbar/src/styles/tabbar.css';

            import * as Tabs from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/tabs/src/index.ts';
            window.UBITS.Tabs = Tabs;
            import '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/tabs/src/styles/tabs.css';

            import * as Toast from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/toast/src/index.ts';
            window.UBITS.Toast = Toast;
            import '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/toast/src/styles/toast.css';

            import * as Toggle from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/toggle/src/index.ts';
            window.UBITS.Toggle = Toggle;
            import '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/toggle/src/styles/toggle.css';

            import * as TokensUbits from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/tokens-ubits/src/index.ts';
            window.UBITS.TokensUbits = TokensUbits;
            
            import * as Tooltip from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/tooltip/src/index.ts';
            window.UBITS.Tooltip = Tooltip;
            import '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/tooltip/src/styles/tooltip.css';
console.log('✅ UBITS Components Bundle Loaded.', window.UBITS);