
    // Auto-generated by scripts/build-components-bundle.ts
    // Defines window.UBITS and attaches all components

    window.UBITS = window.UBITS || {};
    console.log('🔧 Initializing UBITS Components Bundle...');
    
            import * as Accordion from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/accordion/src/index.ts';
            window.UBITS.Accordion = Accordion;
            if (typeof window !== 'undefined') {
                window['createAccordion'] = Accordion.createAccordion;
                window['renderAccordion'] = Accordion.renderAccordion;
                /* Helper for button which might be Button or UbitsButton */
                // if (!window['createAccordion'] && Accordion.create) {
                //      window['createAccordion'] = Accordion.create;
                // }
            }
            
            import * as Alert from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/alert/src/index.ts';
            window.UBITS.Alert = Alert;
            if (typeof window !== 'undefined') {
                window['createAlert'] = Alert.createAlert;
                window['renderAlert'] = Alert.renderAlert;
                /* Helper for button which might be Button or UbitsButton */
                // if (!window['createAlert'] && Alert.create) {
                //      window['createAlert'] = Alert.create;
                // }
            }
            
            import * as Avatar from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/avatar/src/index.ts';
            window.UBITS.Avatar = Avatar;
            if (typeof window !== 'undefined') {
                window['createAvatar'] = Avatar.createAvatar;
                window['renderAvatar'] = Avatar.renderAvatar;
                /* Helper for button which might be Button or UbitsButton */
                // if (!window['createAvatar'] && Avatar.create) {
                //      window['createAvatar'] = Avatar.create;
                // }
            }
            
            import * as Badge from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/badge/src/index.ts';
            window.UBITS.Badge = Badge;
            if (typeof window !== 'undefined') {
                window['createBadge'] = Badge.createBadge;
                window['renderBadge'] = Badge.renderBadge;
                /* Helper for button which might be Button or UbitsButton */
                // if (!window['createBadge'] && Badge.create) {
                //      window['createBadge'] = Badge.create;
                // }
            }
            
            import * as BarMetricCard from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/bar-metric-card/src/index.ts';
            window.UBITS.BarMetricCard = BarMetricCard;
            if (typeof window !== 'undefined') {
                window['createBarMetricCard'] = BarMetricCard.createBarMetricCard;
                window['renderBarMetricCard'] = BarMetricCard.renderBarMetricCard;
                /* Helper for button which might be Button or UbitsButton */
                // if (!window['createBarMetricCard'] && BarMetricCard.create) {
                //      window['createBarMetricCard'] = BarMetricCard.create;
                // }
            }
            
            import * as Breadcrumb from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/breadcrumb/src/index.ts';
            window.UBITS.Breadcrumb = Breadcrumb;
            if (typeof window !== 'undefined') {
                window['createBreadcrumb'] = Breadcrumb.createBreadcrumb;
                window['renderBreadcrumb'] = Breadcrumb.renderBreadcrumb;
                /* Helper for button which might be Button or UbitsButton */
                // if (!window['createBreadcrumb'] && Breadcrumb.create) {
                //      window['createBreadcrumb'] = Breadcrumb.create;
                // }
            }
            
            import * as Button from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/button/src/index.ts';
            window.UBITS.Button = Button;
            if (typeof window !== 'undefined') {
                window['createButton'] = Button.createButton;
                window['renderButton'] = Button.renderButton;
                /* Helper for button which might be Button or UbitsButton */
                // if (!window['createButton'] && Button.create) {
                //      window['createButton'] = Button.create;
                // }
            }
            
            import * as ButtonAi from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/button-ai/src/index.ts';
            window.UBITS.ButtonAi = ButtonAi;
            if (typeof window !== 'undefined') {
                window['createButtonAi'] = ButtonAi.createButtonAi;
                window['renderButtonAi'] = ButtonAi.renderButtonAi;
                /* Helper for button which might be Button or UbitsButton */
                // if (!window['createButtonAi'] && ButtonAi.create) {
                //      window['createButtonAi'] = ButtonAi.create;
                // }
            }
            
            import * as ButtonFeedback from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/button-feedback/src/index.ts';
            window.UBITS.ButtonFeedback = ButtonFeedback;
            if (typeof window !== 'undefined') {
                window['createButtonFeedback'] = ButtonFeedback.createButtonFeedback;
                window['renderButtonFeedback'] = ButtonFeedback.renderButtonFeedback;
                /* Helper for button which might be Button or UbitsButton */
                // if (!window['createButtonFeedback'] && ButtonFeedback.create) {
                //      window['createButtonFeedback'] = ButtonFeedback.create;
                // }
            }
            
            import * as Calendar from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/calendar/src/index.ts';
            window.UBITS.Calendar = Calendar;
            if (typeof window !== 'undefined') {
                window['createCalendar'] = Calendar.createCalendar;
                window['renderCalendar'] = Calendar.renderCalendar;
                /* Helper for button which might be Button or UbitsButton */
                // if (!window['createCalendar'] && Calendar.create) {
                //      window['createCalendar'] = Calendar.create;
                // }
            }
            
            import * as Card from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/card/src/index.ts';
            window.UBITS.Card = Card;
            if (typeof window !== 'undefined') {
                window['createCard'] = Card.createCard;
                window['renderCard'] = Card.renderCard;
                /* Helper for button which might be Button or UbitsButton */
                // if (!window['createCard'] && Card.create) {
                //      window['createCard'] = Card.create;
                // }
            }
            
            import * as Carousel from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/carousel/src/index.ts';
            window.UBITS.Carousel = Carousel;
            if (typeof window !== 'undefined') {
                window['createCarousel'] = Carousel.createCarousel;
                window['renderCarousel'] = Carousel.renderCarousel;
                /* Helper for button which might be Button or UbitsButton */
                // if (!window['createCarousel'] && Carousel.create) {
                //      window['createCarousel'] = Carousel.create;
                // }
            }
            
            import * as Checkbox from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/checkbox/src/index.ts';
            window.UBITS.Checkbox = Checkbox;
            if (typeof window !== 'undefined') {
                window['createCheckbox'] = Checkbox.createCheckbox;
                window['renderCheckbox'] = Checkbox.renderCheckbox;
                /* Helper for button which might be Button or UbitsButton */
                // if (!window['createCheckbox'] && Checkbox.create) {
                //      window['createCheckbox'] = Checkbox.create;
                // }
            }
            
            import * as Chip from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/chip/src/index.ts';
            window.UBITS.Chip = Chip;
            if (typeof window !== 'undefined') {
                window['createChip'] = Chip.createChip;
                window['renderChip'] = Chip.renderChip;
                /* Helper for button which might be Button or UbitsButton */
                // if (!window['createChip'] && Chip.create) {
                //      window['createChip'] = Chip.create;
                // }
            }
            
            import * as CsatMetricCard from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/csat-metric-card/src/index.ts';
            window.UBITS.CsatMetricCard = CsatMetricCard;
            if (typeof window !== 'undefined') {
                window['createCsatMetricCard'] = CsatMetricCard.createCsatMetricCard;
                window['renderCsatMetricCard'] = CsatMetricCard.renderCsatMetricCard;
                /* Helper for button which might be Button or UbitsButton */
                // if (!window['createCsatMetricCard'] && CsatMetricCard.create) {
                //      window['createCsatMetricCard'] = CsatMetricCard.create;
                // }
            }
            
            import * as DataTable from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/data-table/src/index.ts';
            window.UBITS.DataTable = DataTable;
            if (typeof window !== 'undefined') {
                window['createDataTable'] = DataTable.createDataTable;
                window['renderDataTable'] = DataTable.renderDataTable;
                /* Helper for button which might be Button or UbitsButton */
                // if (!window['createDataTable'] && DataTable.create) {
                //      window['createDataTable'] = DataTable.create;
                // }
            }
            
            import * as DataView from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/data-view/src/index.ts';
            window.UBITS.DataView = DataView;
            if (typeof window !== 'undefined') {
                window['createDataView'] = DataView.createDataView;
                window['renderDataView'] = DataView.renderDataView;
                /* Helper for button which might be Button or UbitsButton */
                // if (!window['createDataView'] && DataView.create) {
                //      window['createDataView'] = DataView.create;
                // }
            }
            
            import * as Drawer from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/drawer/src/index.ts';
            window.UBITS.Drawer = Drawer;
            if (typeof window !== 'undefined') {
                window['createDrawer'] = Drawer.createDrawer;
                window['renderDrawer'] = Drawer.renderDrawer;
                /* Helper for button which might be Button or UbitsButton */
                // if (!window['createDrawer'] && Drawer.create) {
                //      window['createDrawer'] = Drawer.create;
                // }
            }
            
            import * as EmptyState from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/empty-state/src/index.ts';
            window.UBITS.EmptyState = EmptyState;
            if (typeof window !== 'undefined') {
                window['createEmptyState'] = EmptyState.createEmptyState;
                window['renderEmptyState'] = EmptyState.renderEmptyState;
                /* Helper for button which might be Button or UbitsButton */
                // if (!window['createEmptyState'] && EmptyState.create) {
                //      window['createEmptyState'] = EmptyState.create;
                // }
            }
            
            import * as FileUpload from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/file-upload/src/index.ts';
            window.UBITS.FileUpload = FileUpload;
            if (typeof window !== 'undefined') {
                window['createFileUpload'] = FileUpload.createFileUpload;
                window['renderFileUpload'] = FileUpload.renderFileUpload;
                /* Helper for button which might be Button or UbitsButton */
                // if (!window['createFileUpload'] && FileUpload.create) {
                //      window['createFileUpload'] = FileUpload.create;
                // }
            }
            
            import * as Gallery from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/gallery/src/index.ts';
            window.UBITS.Gallery = Gallery;
            if (typeof window !== 'undefined') {
                window['createGallery'] = Gallery.createGallery;
                window['renderGallery'] = Gallery.renderGallery;
                /* Helper for button which might be Button or UbitsButton */
                // if (!window['createGallery'] && Gallery.create) {
                //      window['createGallery'] = Gallery.create;
                // }
            }
            
            import * as HeaderSection from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/header-section/src/index.ts';
            window.UBITS.HeaderSection = HeaderSection;
            if (typeof window !== 'undefined') {
                window['createHeaderSection'] = HeaderSection.createHeaderSection;
                window['renderHeaderSection'] = HeaderSection.renderHeaderSection;
                /* Helper for button which might be Button or UbitsButton */
                // if (!window['createHeaderSection'] && HeaderSection.create) {
                //      window['createHeaderSection'] = HeaderSection.create;
                // }
            }
            
            import * as Input from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/input/src/index.ts';
            window.UBITS.Input = Input;
            if (typeof window !== 'undefined') {
                window['createInput'] = Input.createInput;
                window['renderInput'] = Input.renderInput;
                /* Helper for button which might be Button or UbitsButton */
                // if (!window['createInput'] && Input.create) {
                //      window['createInput'] = Input.create;
                // }
            }
            
            import * as List from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/list/src/index.ts';
            window.UBITS.List = List;
            if (typeof window !== 'undefined') {
                window['createList'] = List.createList;
                window['renderList'] = List.renderList;
                /* Helper for button which might be Button or UbitsButton */
                // if (!window['createList'] && List.create) {
                //      window['createList'] = List.create;
                // }
            }
            
            import * as Mask from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/mask/src/index.ts';
            window.UBITS.Mask = Mask;
            if (typeof window !== 'undefined') {
                window['createMask'] = Mask.createMask;
                window['renderMask'] = Mask.renderMask;
                /* Helper for button which might be Button or UbitsButton */
                // if (!window['createMask'] && Mask.create) {
                //      window['createMask'] = Mask.create;
                // }
            }
            
            import * as Menu from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/menu/src/index.ts';
            window.UBITS.Menu = Menu;
            if (typeof window !== 'undefined') {
                window['createMenu'] = Menu.createMenu;
                window['renderMenu'] = Menu.renderMenu;
                /* Helper for button which might be Button or UbitsButton */
                // if (!window['createMenu'] && Menu.create) {
                //      window['createMenu'] = Menu.create;
                // }
            }
            
            import * as MetricCard from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/metric-card/src/index.ts';
            window.UBITS.MetricCard = MetricCard;
            if (typeof window !== 'undefined') {
                window['createMetricCard'] = MetricCard.createMetricCard;
                window['renderMetricCard'] = MetricCard.renderMetricCard;
                /* Helper for button which might be Button or UbitsButton */
                // if (!window['createMetricCard'] && MetricCard.create) {
                //      window['createMetricCard'] = MetricCard.create;
                // }
            }
            
            import * as Modal from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/modal/src/index.ts';
            window.UBITS.Modal = Modal;
            if (typeof window !== 'undefined') {
                window['createModal'] = Modal.createModal;
                window['renderModal'] = Modal.renderModal;
                /* Helper for button which might be Button or UbitsButton */
                // if (!window['createModal'] && Modal.create) {
                //      window['createModal'] = Modal.create;
                // }
            }
            
            import * as NpsCard from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/nps-card/src/index.ts';
            window.UBITS.NpsCard = NpsCard;
            if (typeof window !== 'undefined') {
                window['createNpsCard'] = NpsCard.createNpsCard;
                window['renderNpsCard'] = NpsCard.renderNpsCard;
                /* Helper for button which might be Button or UbitsButton */
                // if (!window['createNpsCard'] && NpsCard.create) {
                //      window['createNpsCard'] = NpsCard.create;
                // }
            }
            
            import * as Pagination from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/pagination/src/index.ts';
            window.UBITS.Pagination = Pagination;
            if (typeof window !== 'undefined') {
                window['createPagination'] = Pagination.createPagination;
                window['renderPagination'] = Pagination.renderPagination;
                /* Helper for button which might be Button or UbitsButton */
                // if (!window['createPagination'] && Pagination.create) {
                //      window['createPagination'] = Pagination.create;
                // }
            }
            
            import * as ParticipantsMenu from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/participants-menu/src/index.ts';
            window.UBITS.ParticipantsMenu = ParticipantsMenu;
            if (typeof window !== 'undefined') {
                window['createParticipantsMenu'] = ParticipantsMenu.createParticipantsMenu;
                window['renderParticipantsMenu'] = ParticipantsMenu.renderParticipantsMenu;
                /* Helper for button which might be Button or UbitsButton */
                // if (!window['createParticipantsMenu'] && ParticipantsMenu.create) {
                //      window['createParticipantsMenu'] = ParticipantsMenu.create;
                // }
            }
            
            import * as Popover from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/popover/src/index.ts';
            window.UBITS.Popover = Popover;
            if (typeof window !== 'undefined') {
                window['createPopover'] = Popover.createPopover;
                window['renderPopover'] = Popover.renderPopover;
                /* Helper for button which might be Button or UbitsButton */
                // if (!window['createPopover'] && Popover.create) {
                //      window['createPopover'] = Popover.create;
                // }
            }
            
            import * as Progress from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/progress/src/index.ts';
            window.UBITS.Progress = Progress;
            if (typeof window !== 'undefined') {
                window['createProgress'] = Progress.createProgress;
                window['renderProgress'] = Progress.renderProgress;
                /* Helper for button which might be Button or UbitsButton */
                // if (!window['createProgress'] && Progress.create) {
                //      window['createProgress'] = Progress.create;
                // }
            }
            
            import * as ProgressGeneralCard from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/progress-general-card/src/index.ts';
            window.UBITS.ProgressGeneralCard = ProgressGeneralCard;
            if (typeof window !== 'undefined') {
                window['createProgressGeneralCard'] = ProgressGeneralCard.createProgressGeneralCard;
                window['renderProgressGeneralCard'] = ProgressGeneralCard.renderProgressGeneralCard;
                /* Helper for button which might be Button or UbitsButton */
                // if (!window['createProgressGeneralCard'] && ProgressGeneralCard.create) {
                //      window['createProgressGeneralCard'] = ProgressGeneralCard.create;
                // }
            }
            
            import * as RadioButton from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/radio-button/src/index.ts';
            window.UBITS.RadioButton = RadioButton;
            if (typeof window !== 'undefined') {
                window['createRadioButton'] = RadioButton.createRadioButton;
                window['renderRadioButton'] = RadioButton.renderRadioButton;
                /* Helper for button which might be Button or UbitsButton */
                // if (!window['createRadioButton'] && RadioButton.create) {
                //      window['createRadioButton'] = RadioButton.create;
                // }
            }
            
            import * as SaveIndicator from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/save-indicator/src/index.ts';
            window.UBITS.SaveIndicator = SaveIndicator;
            if (typeof window !== 'undefined') {
                window['createSaveIndicator'] = SaveIndicator.createSaveIndicator;
                window['renderSaveIndicator'] = SaveIndicator.renderSaveIndicator;
                /* Helper for button which might be Button or UbitsButton */
                // if (!window['createSaveIndicator'] && SaveIndicator.create) {
                //      window['createSaveIndicator'] = SaveIndicator.create;
                // }
            }
            
            import * as ScoreCardMetrics from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/score-card-metrics/src/index.ts';
            window.UBITS.ScoreCardMetrics = ScoreCardMetrics;
            if (typeof window !== 'undefined') {
                window['createScoreCardMetrics'] = ScoreCardMetrics.createScoreCardMetrics;
                window['renderScoreCardMetrics'] = ScoreCardMetrics.renderScoreCardMetrics;
                /* Helper for button which might be Button or UbitsButton */
                // if (!window['createScoreCardMetrics'] && ScoreCardMetrics.create) {
                //      window['createScoreCardMetrics'] = ScoreCardMetrics.create;
                // }
            }
            
            import * as Scroll from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/scroll/src/index.ts';
            window.UBITS.Scroll = Scroll;
            if (typeof window !== 'undefined') {
                window['createScroll'] = Scroll.createScroll;
                window['renderScroll'] = Scroll.renderScroll;
                /* Helper for button which might be Button or UbitsButton */
                // if (!window['createScroll'] && Scroll.create) {
                //      window['createScroll'] = Scroll.create;
                // }
            }
            
            import * as SearchButton from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/search-button/src/index.ts';
            window.UBITS.SearchButton = SearchButton;
            if (typeof window !== 'undefined') {
                window['createSearchButton'] = SearchButton.createSearchButton;
                window['renderSearchButton'] = SearchButton.renderSearchButton;
                /* Helper for button which might be Button or UbitsButton */
                // if (!window['createSearchButton'] && SearchButton.create) {
                //      window['createSearchButton'] = SearchButton.create;
                // }
            }
            
            import * as SegmentControl from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/segment-control/src/index.ts';
            window.UBITS.SegmentControl = SegmentControl;
            if (typeof window !== 'undefined') {
                window['createSegmentControl'] = SegmentControl.createSegmentControl;
                window['renderSegmentControl'] = SegmentControl.renderSegmentControl;
                /* Helper for button which might be Button or UbitsButton */
                // if (!window['createSegmentControl'] && SegmentControl.create) {
                //      window['createSegmentControl'] = SegmentControl.create;
                // }
            }
            
            import * as SelectionCard from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/selection-card/src/index.ts';
            window.UBITS.SelectionCard = SelectionCard;
            if (typeof window !== 'undefined') {
                window['createSelectionCard'] = SelectionCard.createSelectionCard;
                window['renderSelectionCard'] = SelectionCard.renderSelectionCard;
                /* Helper for button which might be Button or UbitsButton */
                // if (!window['createSelectionCard'] && SelectionCard.create) {
                //      window['createSelectionCard'] = SelectionCard.create;
                // }
            }
            
            import * as Sidebar from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/sidebar/src/index.ts';
            window.UBITS.Sidebar = Sidebar;
            if (typeof window !== 'undefined') {
                window['createSidebar'] = Sidebar.createSidebar;
                window['renderSidebar'] = Sidebar.renderSidebar;
                /* Helper for button which might be Button or UbitsButton */
                // if (!window['createSidebar'] && Sidebar.create) {
                //      window['createSidebar'] = Sidebar.create;
                // }
            }
            
            import * as Skeleton from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/skeleton/src/index.ts';
            window.UBITS.Skeleton = Skeleton;
            if (typeof window !== 'undefined') {
                window['createSkeleton'] = Skeleton.createSkeleton;
                window['renderSkeleton'] = Skeleton.renderSkeleton;
                /* Helper for button which might be Button or UbitsButton */
                // if (!window['createSkeleton'] && Skeleton.create) {
                //      window['createSkeleton'] = Skeleton.create;
                // }
            }
            
            import * as Slider from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/slider/src/index.ts';
            window.UBITS.Slider = Slider;
            if (typeof window !== 'undefined') {
                window['createSlider'] = Slider.createSlider;
                window['renderSlider'] = Slider.renderSlider;
                /* Helper for button which might be Button or UbitsButton */
                // if (!window['createSlider'] && Slider.create) {
                //      window['createSlider'] = Slider.create;
                // }
            }
            
            import * as Spinner from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/spinner/src/index.ts';
            window.UBITS.Spinner = Spinner;
            if (typeof window !== 'undefined') {
                window['createSpinner'] = Spinner.createSpinner;
                window['renderSpinner'] = Spinner.renderSpinner;
                /* Helper for button which might be Button or UbitsButton */
                // if (!window['createSpinner'] && Spinner.create) {
                //      window['createSpinner'] = Spinner.create;
                // }
            }
            
            import * as StatsCard from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/stats-card/src/index.ts';
            window.UBITS.StatsCard = StatsCard;
            if (typeof window !== 'undefined') {
                window['createStatsCard'] = StatsCard.createStatsCard;
                window['renderStatsCard'] = StatsCard.renderStatsCard;
                /* Helper for button which might be Button or UbitsButton */
                // if (!window['createStatsCard'] && StatsCard.create) {
                //      window['createStatsCard'] = StatsCard.create;
                // }
            }
            
            import * as StatusTag from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/status-tag/src/index.ts';
            window.UBITS.StatusTag = StatusTag;
            if (typeof window !== 'undefined') {
                window['createStatusTag'] = StatusTag.createStatusTag;
                window['renderStatusTag'] = StatusTag.renderStatusTag;
                /* Helper for button which might be Button or UbitsButton */
                // if (!window['createStatusTag'] && StatusTag.create) {
                //      window['createStatusTag'] = StatusTag.create;
                // }
            }
            
            import * as Stepper from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/stepper/src/index.ts';
            window.UBITS.Stepper = Stepper;
            if (typeof window !== 'undefined') {
                window['createStepper'] = Stepper.createStepper;
                window['renderStepper'] = Stepper.renderStepper;
                /* Helper for button which might be Button or UbitsButton */
                // if (!window['createStepper'] && Stepper.create) {
                //      window['createStepper'] = Stepper.create;
                // }
            }
            
            import * as Subnav from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/subnav/src/index.ts';
            window.UBITS.Subnav = Subnav;
            if (typeof window !== 'undefined') {
                window['createSubnav'] = Subnav.createSubnav;
                window['renderSubnav'] = Subnav.renderSubnav;
                /* Helper for button which might be Button or UbitsButton */
                // if (!window['createSubnav'] && Subnav.create) {
                //      window['createSubnav'] = Subnav.create;
                // }
            }
            
            import * as Tabbar from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/tabbar/src/index.ts';
            window.UBITS.Tabbar = Tabbar;
            if (typeof window !== 'undefined') {
                window['createTabbar'] = Tabbar.createTabbar;
                window['renderTabbar'] = Tabbar.renderTabbar;
                /* Helper for button which might be Button or UbitsButton */
                // if (!window['createTabbar'] && Tabbar.create) {
                //      window['createTabbar'] = Tabbar.create;
                // }
            }
            
            import * as Tabs from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/tabs/src/index.ts';
            window.UBITS.Tabs = Tabs;
            if (typeof window !== 'undefined') {
                window['createTabs'] = Tabs.createTabs;
                window['renderTabs'] = Tabs.renderTabs;
                /* Helper for button which might be Button or UbitsButton */
                // if (!window['createTabs'] && Tabs.create) {
                //      window['createTabs'] = Tabs.create;
                // }
            }
            
            import * as Toast from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/toast/src/index.ts';
            window.UBITS.Toast = Toast;
            if (typeof window !== 'undefined') {
                window['createToast'] = Toast.createToast;
                window['renderToast'] = Toast.renderToast;
                /* Helper for button which might be Button or UbitsButton */
                // if (!window['createToast'] && Toast.create) {
                //      window['createToast'] = Toast.create;
                // }
            }
            
            import * as Toggle from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/toggle/src/index.ts';
            window.UBITS.Toggle = Toggle;
            if (typeof window !== 'undefined') {
                window['createToggle'] = Toggle.createToggle;
                window['renderToggle'] = Toggle.renderToggle;
                /* Helper for button which might be Button or UbitsButton */
                // if (!window['createToggle'] && Toggle.create) {
                //      window['createToggle'] = Toggle.create;
                // }
            }
            
            import * as TokensUbits from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/tokens-ubits/src/index.ts';
            window.UBITS.TokensUbits = TokensUbits;
            if (typeof window !== 'undefined') {
                window['createTokensUbits'] = TokensUbits.createTokensUbits;
                window['renderTokensUbits'] = TokensUbits.renderTokensUbits;
                /* Helper for button which might be Button or UbitsButton */
                // if (!window['createTokensUbits'] && TokensUbits.create) {
                //      window['createTokensUbits'] = TokensUbits.create;
                // }
            }
            
            import * as Tooltip from '/Users/ub-col-pro-lf4/Desktop/Autorun/vendor/ubits/packages/components/tooltip/src/index.ts';
            window.UBITS.Tooltip = Tooltip;
            if (typeof window !== 'undefined') {
                window['createTooltip'] = Tooltip.createTooltip;
                window['renderTooltip'] = Tooltip.renderTooltip;
                /* Helper for button which might be Button or UbitsButton */
                // if (!window['createTooltip'] && Tooltip.create) {
                //      window['createTooltip'] = Tooltip.create;
                // }
            }
            console.log('✅ UBITS Components Bundle Loaded.', window.UBITS);