
import fs from 'node:fs';
import path from 'node:path';
import { build } from 'vite';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');
const COMPONENTS_DIR = path.resolve(ROOT, 'vendor/ubits/packages/components');
const OUTPUT_DIR = path.resolve(ROOT, 'vendor/ubits/packages/templates/dist');

async function main() {
    console.log('🚀 Starting Component Build...');

    // 1. Scan Components
    if (!fs.existsSync(COMPONENTS_DIR)) {
        console.error(`❌ Components directory not found: ${COMPONENTS_DIR}`);
        process.exit(1);
    }

    const components = fs.readdirSync(COMPONENTS_DIR).filter(file => {
        return fs.statSync(path.join(COMPONENTS_DIR, file)).isDirectory();
    });

    console.log(`📦 Found ${components.length} components.`);

    // 2. Generate Entry File Content
    let entryContent = `
    // Auto-generated by scripts/build-components-bundle.ts
    // Defines window.UBITS and attaches all components

    window.UBITS = window.UBITS || {};
    console.log('🔧 Initializing UBITS Components Bundle...');
    `;

    for (const component of components) {
        const compPath = path.join(COMPONENTS_DIR, component);
        const srcPath = path.join(compPath, 'src');
        const indexPath = path.join(srcPath, 'index.ts');

        // Check if index.ts exists
        if (fs.existsSync(indexPath)) {
            // PascalCase converter for namespace
            const namespace = component
                .split('-')
                .map(part => part.charAt(0).toUpperCase() + part.slice(1))
                .join('');

            // Import JS
            entryContent += `
            import * as ${namespace} from '${indexPath}';
            window.UBITS.${namespace} = ${namespace};
            `;

            // Scan for CSS files in src/styles/
            const stylesDir = path.join(srcPath, 'styles');
            if (fs.existsSync(stylesDir) && fs.statSync(stylesDir).isDirectory()) {
                const cssFiles = fs.readdirSync(stylesDir).filter(f => f.endsWith('.css'));
                for (const css of cssFiles) {
                    const cssPath = path.join(stylesDir, css);
                    entryContent += `import '${cssPath}';\n`;
                }
            }
        }
    }

    entryContent += `console.log('✅ UBITS Components Bundle Loaded.', window.UBITS);`;

    const tempEntryPath = path.resolve(ROOT, 'temp-components-entry.ts');
    fs.writeFileSync(tempEntryPath, entryContent);
    console.log(`📝 Generated temp entry file: ${tempEntryPath}`);
    console.log(`📂 CWD: ${process.cwd()}`);

    // Ensure output directory exists
    if (!fs.existsSync(OUTPUT_DIR)) {
        console.log(`📁 Creating output directory: ${OUTPUT_DIR}`);
        fs.mkdirSync(OUTPUT_DIR, { recursive: true });
    }





    // 3. Run Vite Build
    try {
        console.log('🔨 Running Vite Build...');
        console.log(`📂 Output config: ${OUTPUT_DIR}`);

        const result = await build({
            root: ROOT,
            configFile: false,
            logLevel: 'info',
            build: {
                outDir: OUTPUT_DIR,
                emptyOutDir: false,
                lib: {
                    entry: tempEntryPath,
                    name: 'UBITSBundle',
                    fileName: () => 'components-bundle.js',
                    formats: ['iife'],
                },
                rollupOptions: {
                    output: {
                        assetFileNames: (assetInfo) => {
                            if (assetInfo.name === 'style.css') return 'components-bundle.css';
                            return assetInfo.name || 'assets/[name]-[hash][extname]';
                        },
                        name: 'UBITSBundle',
                        extend: true
                    }
                },
                minify: false,
                sourcemap: false
            }
        });
        console.log(`✅ Build Success! Result:`, result ? 'Object returned' : 'null');
        console.log(`Contents of output dir:`, fs.readdirSync(OUTPUT_DIR));
    } catch (error) {
        console.error('❌ Build Failed:', error);
    } finally {
        // Cleanup
        if (fs.existsSync(tempEntryPath)) {
            // fs.unlinkSync(tempEntryPath);
            console.log('🧹 [DEBUG] Preserved temp entry file for inspection.');
        }
    }
}

main();
